#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""pipecat-quickstart - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Deepgram (Speech-to-Text)
- Openai_Responses (LLM)
- Cartesia (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""


from pipecat.services.openai.responses.llm import OpenAIResponsesLLMService
from pipecat.services.cartesia.tts import CartesiaTTSService
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.transports.base_transport import BaseTransport
from pipecat.frames.frames import LLMRunFrame
from pipecat.runner.types import RunnerArguments
from dotenv import load_dotenv
from pipecat.runner.types import SmallWebRTCRunnerArguments
from pipecat.transports.base_transport import TransportParams
from pipecat.transports.smallwebrtc.connection import SmallWebRTCConnection
from loguru import logger
from pipecat.transports.daily.transport import DailyTransport, DailyParams
from pipecat.pipeline.pipeline import Pipeline
from pipecat.runner.types import DailyRunnerArguments
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.transports.smallwebrtc.transport import SmallWebRTCTransport
import os
import json
from pipecat.pipeline.task import PipelineParams, PipelineTask
from pipecat.pipeline.runner import PipelineRunner
from pipecat.processors.aggregators.llm_response_universal import LLMContextAggregatorPair, LLMUserAggregatorParams
from pipecat.services.deepgram.stt import DeepgramSTTService
from pipecat.processors.frameworks.rtvi.observer import RTVIObserverParams
from fastapi import Request
from fastapi.responses import JSONResponse
from pipecat.runner.run import app
from openai import AsyncOpenAI

load_dotenv(override=True)


@app.post("/api/correct")
async def correct_grammar(request: Request):
    try:
        body = await request.json()
        sentence = body.get("sentence", "").strip()
        if not sentence:
            return JSONResponse({"corrections": []})

        logger.info(f"[correct] checking: {sentence!r}")

        client = AsyncOpenAI(api_key=os.getenv("OPENAI_API_KEY"))
        response = await client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a strict English checker for non-native speakers. "
                        "The input is a voice transcription that may contain speech recognition errors "
                        "(a spoken word transcribed as a different but valid English word). "
                        "Identify every error including: grammar mistakes AND words that are clearly wrong "
                        "in context because they make no semantic sense as used (likely a transcription error). "
                        "Cover: verb tense, subject-verb agreement, articles, prepositions, "
                        "auxiliary verbs, double subjects, plural/singular, word form, "
                        "and words that are semantically impossible in their grammatical position. "
                        "For each error return the SMALLEST possible span of consecutive words from the sentence "
                        "that isolates the mistake — ideally just the wrong word or two, not the whole clause. "
                        "The 'wrong' field must be copied verbatim from the sentence. "
                        "Do not flag names, style choices, or valid alternative phrasings. "
                        "Return ONLY a JSON array of {\"wrong\": \"...\", \"right\": \"...\"} objects. "
                        "If no errors, return []. No markdown, no explanation."
                    ),
                },
                {"role": "user", "content": sentence},
            ],
            temperature=0,
        )

        raw = response.choices[0].message.content.strip()
        logger.info(f"[correct] raw response: {raw!r}")

        # Strip markdown code fences if present
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
        try:
            corrections = json.loads(raw)
        except Exception:
            corrections = []

        # Discard corrections where "wrong" doesn't appear verbatim in the sentence
        sentence_lower = sentence.lower()
        corrections = [
            c for c in corrections
            if isinstance(c, dict)
            and "wrong" in c and "right" in c
            and c["wrong"].lower() in sentence_lower
        ]

        logger.info(f"[correct] corrections: {corrections}")
        return JSONResponse({"corrections": corrections})
    except Exception as e:
        logger.error(f"[correct] error: {e}")
        return JSONResponse({"corrections": []}, status_code=500)




async def run_bot(transport: BaseTransport):
    """Main bot logic."""
    logger.info("Starting bot")

    # Speech-to-Text service
    stt = DeepgramSTTService(api_key=os.getenv("DEEPGRAM_API_KEY"), verbose=True)

    # Text-to-Speech service
    tts = CartesiaTTSService(
            api_key=os.getenv("CARTESIA_API_KEY"),
            settings=CartesiaTTSService.Settings(
                voice=os.getenv("CARTESIA_VOICE_ID", "71a7ad14-091c-4e8e-a314-022ece01c121"),
            ),
        )


    # LLM service
    llm = OpenAIResponsesLLMService(
            api_key=os.getenv("OPENAI_API_KEY"),
            settings=OpenAIResponsesLLMService.Settings(
                model=os.getenv("OPENAI_MODEL", "gpt-4o-mini"),
                system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can't be spoken. Respond to what the user said in a creative, helpful, and brief way.",
            ),
        )



    context = LLMContext()
    user_aggregator, assistant_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(
            vad_analyzer=SileroVADAnalyzer(),    ),
    )


    


    # Pipeline - assembled from reusable components
    pipeline = Pipeline([
        transport.input(),

        stt,

        user_aggregator,

        llm,

        tts,

        
        transport.output(),

        
        assistant_aggregator,

    ])


    task = PipelineTask(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        rtvi_observer_params=RTVIObserverParams(
            user_transcription_enabled=True,
            user_speaking_enabled=True,
            bot_tts_enabled=True,
        ),
    )

    @task.rtvi.event_handler("on_client_ready")
    async def on_client_ready(rtvi):
        # Kick off the conversation
        context.add_message({"role": "user", "content": "Please introduce yourself."})
        await task.queue_frames([LLMRunFrame()])

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await task.cancel()




    runner = PipelineRunner(handle_sigint=False)

    await runner.run(task)


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""

    transport = None

    match runner_args:
        case DailyRunnerArguments():
            transport = DailyTransport(
                runner_args.room_url,
                runner_args.token,
                "Pipecat Bot",
                params=DailyParams(
                    audio_in_enabled=True,
                    audio_out_enabled=True,
                ),
            )
        case SmallWebRTCRunnerArguments():
            webrtc_connection: SmallWebRTCConnection = runner_args.webrtc_connection

            transport = SmallWebRTCTransport(
                webrtc_connection=webrtc_connection,
                params=TransportParams(
                    audio_in_enabled=True,
                    audio_out_enabled=True,
                ),
            )
        case _:
            logger.error(f"Unsupported runner arguments type: {type(runner_args)}")
            return

    await run_bot(transport)


if __name__ == "__main__":
    from pipecat.runner.run import main

    main()